version: '3.4'

services:
  bartender:
    image: ${DOCKER_REGISTRY-}bartender
    build:
      context: .
      dockerfile: Bartender/Dockerfile
    ports:
     - 49210:80
     - 49209:443

  busboy:
    image: ${DOCKER_REGISTRY-}busboy
    build:
      context: .
      dockerfile: BusBoy/Dockerfile
    ports:
     - 49177:443


  kitchen:
    image: ${DOCKER_REGISTRY-}kitchen
    build:
      context: .
      dockerfile: Kitchen/Dockerfile
    ports:
     - 49175:443


  hostess:
    image: ${DOCKER_REGISTRY-}hostess
    build:
      context: .
      dockerfile: Hostess/Dockerfile
    ports:
     - 49173:443


  waiter:
    image: ${DOCKER_REGISTRY-}waiter
    build:
      context: .
      dockerfile: Waiter/Dockerfile
    ports:
     - 49180:443

